---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: spring-kubernetes-secret-tutorial
  name: db-secret
type: Opaque
data:
  DB_USERNAME: dXNlcm5hbWU=     # base64 encoded username
  DB_PASSWORD: cGFzc3dvcmQ=     # base64 encoded password

---
# Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-kubernetes-secret-tutorial
  name: spring-kubernetes-secret-tutorial
  namespace: default
spec:
  selector:
    matchLabels:
      app: spring-kubernetes-secret-tutorial
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: spring-kubernetes-secret-tutorial
      name: spring-kubernetes-secret-tutorial
      namespace: default
    spec:
      containers:
        - image: spring-kubernetes-secret-tutorial:1.0.0
          imagePullPolicy: IfNotPresent
          name: container-0
          ports:
            - containerPort: 8080 # Internal port
              name: http
              protocol: TCP
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
        
      restartPolicy: Always
---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-kubernetes-secret-tutorial
  name: spring-kubernetes-secret-tutorial
  namespace: default
spec:
  ports:
    - name: http
      port: 8080 # The port exposed by the service
      protocol: TCP
      targetPort: 8080 # Internal port
  selector:
    app: spring-kubernetes-secret-tutorial
  sessionAffinity: None
  type: LoadBalancer # type of the service. LoadBalancer indicates that our service will be external.
